version: '3'

services:
  web0001:
    image: localhost:5000/nginx-app
    build: .
    ports:
      - 80
    restart: always
    deploy:
      placement:
        constraints: [node.role == manager]
        
  web0002:
    image: localhost:5000/nginx-app
    ports:
      - 80
    restart: always
    deploy:
      placement:
        constraints: [node.role == worker]
